version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Build Docker image
          command: |
            docker build -t pain0383/flask-app:latest .
      - run:
          name: Push to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "pain0383" --password-stdin
            docker push pain0383/flask-app:latest

workflows:
  build-and-push:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: master
